# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm install'
- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'snykconnection'
    testType: 'app'
    severityThreshold: 'medium'
    monitorOnBuild: true
    failOnIssues: false
    projectName: 'snyktesting'
    organization: 'mayankbansal0105'
